// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentDecision struct {
	ID            string             `json:"id"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	DecisionType  string             `json:"decision_type"`
	Title         string             `json:"title"`
	Summary       string             `json:"summary"`
	Inputs        []byte             `json:"inputs"`
	Action        []byte             `json:"action"`
	ConfidencePct int32              `json:"confidence_pct"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Bundle struct {
	ID            string             `json:"id"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	Status        string             `json:"status"`
	TipLamports   int64              `json:"tip_lamports"`
	TargetSlot    pgtype.Int8        `json:"target_slot"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	LandedAt      pgtype.Timestamptz `json:"landed_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ChartPoint struct {
	ID        int64              `json:"id"`
	Series    string             `json:"series"`
	PointTime pgtype.Timestamptz `json:"point_time"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Failure struct {
	ID                string             `json:"id"`
	TransactionID     pgtype.Text        `json:"transaction_id"`
	BundleID          pgtype.Text        `json:"bundle_id"`
	Kind              string             `json:"kind"`
	Title             string             `json:"title"`
	Severity          string             `json:"severity"`
	Slot              pgtype.Int8        `json:"slot"`
	RecommendedAction pgtype.Text        `json:"recommended_action"`
	Evidence          []byte             `json:"evidence"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type LifecycleEvent struct {
	ID            string             `json:"id"`
	TransactionID string             `json:"transaction_id"`
	Signature     pgtype.Text        `json:"signature"`
	BundleID      pgtype.Text        `json:"bundle_id"`
	Stage         string             `json:"stage"`
	Slot          pgtype.Int8        `json:"slot"`
	LatencyMs     pgtype.Int8        `json:"latency_ms"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RecoveryAction struct {
	ID            string             `json:"id"`
	TransactionID string             `json:"transaction_id"`
	DecisionID    pgtype.Text        `json:"decision_id"`
	Label         string             `json:"label"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID                   string             `json:"id"`
	Signature            pgtype.Text        `json:"signature"`
	BundleID             pgtype.Text        `json:"bundle_id"`
	SubmissionKind       string             `json:"submission_kind"`
	Encoding             string             `json:"encoding"`
	Signatures           []byte             `json:"signatures"`
	TxCount              int32              `json:"tx_count"`
	Status               string             `json:"status"`
	Stage                string             `json:"stage"`
	PolicyMode           string             `json:"policy_mode"`
	TipLamports          int64              `json:"tip_lamports"`
	RequestedTipLamports int64              `json:"requested_tip_lamports"`
	FloorLamports        int64              `json:"floor_lamports"`
	TipSource            string             `json:"tip_source"`
	TargetSlot           pgtype.Int8        `json:"target_slot"`
	SubmittedSlot        pgtype.Int8        `json:"submitted_slot"`
	ProcessedSlot        pgtype.Int8        `json:"processed_slot"`
	ConfirmedSlot        pgtype.Int8        `json:"confirmed_slot"`
	FinalizedSlot        pgtype.Int8        `json:"finalized_slot"`
	Leader               pgtype.Text        `json:"leader"`
	RetryAttempt         int32              `json:"retry_attempt"`
	FailureKind          pgtype.Text        `json:"failure_kind"`
	AgentDecisionID      pgtype.Text        `json:"agent_decision_id"`
	Memo                 pgtype.Text        `json:"memo"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ProcessedAt          pgtype.Timestamptz `json:"processed_at"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
	FinalizedAt          pgtype.Timestamptz `json:"finalized_at"`
	FailedAt             pgtype.Timestamptz `json:"failed_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Webhook struct {
	ID        string             `json:"id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID             string             `json:"id"`
	WebhookID      string             `json:"webhook_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	ResponseCode   pgtype.Int4        `json:"response_code"`
	RetryCount     int32              `json:"retry_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}
