// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avgProcessedToConfirmedMS = `-- name: AvgProcessedToConfirmedMS :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (confirmed_at - processed_at)) * 1000), 0)::float8
FROM transactions WHERE processed_at IS NOT NULL AND confirmed_at IS NOT NULL AND confirmed_at >= NOW() - INTERVAL '15 minutes'
`

func (q *Queries) AvgProcessedToConfirmedMS(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, avgProcessedToConfirmedMS)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const avgTipLamports = `-- name: AvgTipLamports :one
SELECT COALESCE(AVG(tip_lamports), 0)::float8 FROM bundles WHERE tip_lamports > 0
`

func (q *Queries) AvgTipLamports(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, avgTipLamports)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const countBundleMetrics = `-- name: CountBundleMetrics :one
SELECT
    COUNT(*)::bigint AS sent,
    COUNT(*) FILTER (WHERE status = 'landed')::bigint AS landed,
    COUNT(*) FILTER (WHERE status IN ('pending', 'submitted'))::bigint AS pending
FROM bundles
`

type CountBundleMetricsRow struct {
	Sent    int64 `json:"sent"`
	Landed  int64 `json:"landed"`
	Pending int64 `json:"pending"`
}

func (q *Queries) CountBundleMetrics(ctx context.Context) (CountBundleMetricsRow, error) {
	row := q.db.QueryRow(ctx, countBundleMetrics)
	var i CountBundleMetricsRow
	err := row.Scan(&i.Sent, &i.Landed, &i.Pending)
	return i, err
}

const countFailuresToday = `-- name: CountFailuresToday :one
SELECT COUNT(*)::bigint FROM failures WHERE created_at >= CURRENT_DATE
`

func (q *Queries) CountFailuresToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFailuresToday)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRetries = `-- name: CountRetries :one
SELECT COALESCE(SUM(retry_attempt), 0)::bigint FROM transactions
`

func (q *Queries) CountRetries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRetries)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTransactionsByStage = `-- name: CountTransactionsByStage :many
SELECT stage, COUNT(*)::bigint AS count FROM transactions GROUP BY stage
`

type CountTransactionsByStageRow struct {
	Stage string `json:"stage"`
	Count int64  `json:"count"`
}

func (q *Queries) CountTransactionsByStage(ctx context.Context) ([]CountTransactionsByStageRow, error) {
	rows, err := q.db.Query(ctx, countTransactionsByStage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTransactionsByStageRow{}
	for rows.Next() {
		var i CountTransactionsByStageRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBundle = `-- name: CreateBundle :one
INSERT INTO bundles (id, transaction_id, status, tip_lamports, target_slot, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, status, tip_lamports, target_slot, submitted_at, landed_at, failed_at, created_at
`

type CreateBundleParams struct {
	ID            string             `json:"id"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	Status        string             `json:"status"`
	TipLamports   int64              `json:"tip_lamports"`
	TargetSlot    pgtype.Int8        `json:"target_slot"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error) {
	row := q.db.QueryRow(ctx, createBundle,
		arg.ID,
		arg.TransactionID,
		arg.Status,
		arg.TipLamports,
		arg.TargetSlot,
		arg.SubmittedAt,
	)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Status,
		&i.TipLamports,
		&i.TargetSlot,
		&i.SubmittedAt,
		&i.LandedAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, status, stage, policy_mode, tip_lamports, requested_tip_lamports,
    floor_lamports, tip_source, memo, retry_attempt,
    submission_kind, encoding, signatures, tx_count, signature, bundle_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16
) RETURNING id, signature, bundle_id, submission_kind, encoding, signatures, tx_count, status, stage, policy_mode, tip_lamports, requested_tip_lamports, floor_lamports, tip_source, target_slot, submitted_slot, processed_slot, confirmed_slot, finalized_slot, leader, retry_attempt, failure_kind, agent_decision_id, memo, created_at, submitted_at, processed_at, confirmed_at, finalized_at, failed_at, updated_at
`

type CreateTransactionParams struct {
	ID                   string      `json:"id"`
	Status               string      `json:"status"`
	Stage                string      `json:"stage"`
	PolicyMode           string      `json:"policy_mode"`
	TipLamports          int64       `json:"tip_lamports"`
	RequestedTipLamports int64       `json:"requested_tip_lamports"`
	FloorLamports        int64       `json:"floor_lamports"`
	TipSource            string      `json:"tip_source"`
	Memo                 pgtype.Text `json:"memo"`
	RetryAttempt         int32       `json:"retry_attempt"`
	SubmissionKind       string      `json:"submission_kind"`
	Encoding             string      `json:"encoding"`
	Signatures           []byte      `json:"signatures"`
	TxCount              int32       `json:"tx_count"`
	Signature            pgtype.Text `json:"signature"`
	BundleID             pgtype.Text `json:"bundle_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.PolicyMode,
		arg.TipLamports,
		arg.RequestedTipLamports,
		arg.FloorLamports,
		arg.TipSource,
		arg.Memo,
		arg.RetryAttempt,
		arg.SubmissionKind,
		arg.Encoding,
		arg.Signatures,
		arg.TxCount,
		arg.Signature,
		arg.BundleID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Signature,
		&i.BundleID,
		&i.SubmissionKind,
		&i.Encoding,
		&i.Signatures,
		&i.TxCount,
		&i.Status,
		&i.Stage,
		&i.PolicyMode,
		&i.TipLamports,
		&i.RequestedTipLamports,
		&i.FloorLamports,
		&i.TipSource,
		&i.TargetSlot,
		&i.SubmittedSlot,
		&i.ProcessedSlot,
		&i.ConfirmedSlot,
		&i.FinalizedSlot,
		&i.Leader,
		&i.RetryAttempt,
		&i.FailureKind,
		&i.AgentDecisionID,
		&i.Memo,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.ProcessedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBundle = `-- name: GetBundle :one
SELECT id, transaction_id, status, tip_lamports, target_slot, submitted_at, landed_at, failed_at, created_at FROM bundles WHERE id = $1
`

func (q *Queries) GetBundle(ctx context.Context, id string) (Bundle, error) {
	row := q.db.QueryRow(ctx, getBundle, id)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Status,
		&i.TipLamports,
		&i.TargetSlot,
		&i.SubmittedAt,
		&i.LandedAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, signature, bundle_id, submission_kind, encoding, signatures, tx_count, status, stage, policy_mode, tip_lamports, requested_tip_lamports, floor_lamports, tip_source, target_slot, submitted_slot, processed_slot, confirmed_slot, finalized_slot, leader, retry_attempt, failure_kind, agent_decision_id, memo, created_at, submitted_at, processed_at, confirmed_at, finalized_at, failed_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Signature,
		&i.BundleID,
		&i.SubmissionKind,
		&i.Encoding,
		&i.Signatures,
		&i.TxCount,
		&i.Status,
		&i.Stage,
		&i.PolicyMode,
		&i.TipLamports,
		&i.RequestedTipLamports,
		&i.FloorLamports,
		&i.TipSource,
		&i.TargetSlot,
		&i.SubmittedSlot,
		&i.ProcessedSlot,
		&i.ConfirmedSlot,
		&i.FinalizedSlot,
		&i.Leader,
		&i.RetryAttempt,
		&i.FailureKind,
		&i.AgentDecisionID,
		&i.Memo,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.ProcessedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionBySignature = `-- name: GetTransactionBySignature :one
SELECT id, signature, bundle_id, submission_kind, encoding, signatures, tx_count, status, stage, policy_mode, tip_lamports, requested_tip_lamports, floor_lamports, tip_source, target_slot, submitted_slot, processed_slot, confirmed_slot, finalized_slot, leader, retry_attempt, failure_kind, agent_decision_id, memo, created_at, submitted_at, processed_at, confirmed_at, finalized_at, failed_at, updated_at FROM transactions WHERE signature = $1
`

func (q *Queries) GetTransactionBySignature(ctx context.Context, signature pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionBySignature, signature)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Signature,
		&i.BundleID,
		&i.SubmissionKind,
		&i.Encoding,
		&i.Signatures,
		&i.TxCount,
		&i.Status,
		&i.Stage,
		&i.PolicyMode,
		&i.TipLamports,
		&i.RequestedTipLamports,
		&i.FloorLamports,
		&i.TipSource,
		&i.TargetSlot,
		&i.SubmittedSlot,
		&i.ProcessedSlot,
		&i.ConfirmedSlot,
		&i.FinalizedSlot,
		&i.Leader,
		&i.RetryAttempt,
		&i.FailureKind,
		&i.AgentDecisionID,
		&i.Memo,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.ProcessedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentDecision = `-- name: InsertAgentDecision :one
INSERT INTO agent_decisions (
    id, transaction_id, decision_type, title, summary, inputs, action, confidence_pct
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, transaction_id, decision_type, title, summary, inputs, action, confidence_pct, created_at
`

type InsertAgentDecisionParams struct {
	ID            string      `json:"id"`
	TransactionID pgtype.Text `json:"transaction_id"`
	DecisionType  string      `json:"decision_type"`
	Title         string      `json:"title"`
	Summary       string      `json:"summary"`
	Inputs        []byte      `json:"inputs"`
	Action        []byte      `json:"action"`
	ConfidencePct int32       `json:"confidence_pct"`
}

func (q *Queries) InsertAgentDecision(ctx context.Context, arg InsertAgentDecisionParams) (AgentDecision, error) {
	row := q.db.QueryRow(ctx, insertAgentDecision,
		arg.ID,
		arg.TransactionID,
		arg.DecisionType,
		arg.Title,
		arg.Summary,
		arg.Inputs,
		arg.Action,
		arg.ConfidencePct,
	)
	var i AgentDecision
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.DecisionType,
		&i.Title,
		&i.Summary,
		&i.Inputs,
		&i.Action,
		&i.ConfidencePct,
		&i.CreatedAt,
	)
	return i, err
}

const insertChartPoint = `-- name: InsertChartPoint :exec
INSERT INTO chart_points (series, point_time, payload) VALUES ($1, $2, $3)
`

type InsertChartPointParams struct {
	Series    string             `json:"series"`
	PointTime pgtype.Timestamptz `json:"point_time"`
	Payload   []byte             `json:"payload"`
}

func (q *Queries) InsertChartPoint(ctx context.Context, arg InsertChartPointParams) error {
	_, err := q.db.Exec(ctx, insertChartPoint, arg.Series, arg.PointTime, arg.Payload)
	return err
}

const insertFailure = `-- name: InsertFailure :one
INSERT INTO failures (
    id, transaction_id, bundle_id, kind, title, severity, slot, recommended_action, evidence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, transaction_id, bundle_id, kind, title, severity, slot, recommended_action, evidence, created_at
`

type InsertFailureParams struct {
	ID                string      `json:"id"`
	TransactionID     pgtype.Text `json:"transaction_id"`
	BundleID          pgtype.Text `json:"bundle_id"`
	Kind              string      `json:"kind"`
	Title             string      `json:"title"`
	Severity          string      `json:"severity"`
	Slot              pgtype.Int8 `json:"slot"`
	RecommendedAction pgtype.Text `json:"recommended_action"`
	Evidence          []byte      `json:"evidence"`
}

func (q *Queries) InsertFailure(ctx context.Context, arg InsertFailureParams) (Failure, error) {
	row := q.db.QueryRow(ctx, insertFailure,
		arg.ID,
		arg.TransactionID,
		arg.BundleID,
		arg.Kind,
		arg.Title,
		arg.Severity,
		arg.Slot,
		arg.RecommendedAction,
		arg.Evidence,
	)
	var i Failure
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.BundleID,
		&i.Kind,
		&i.Title,
		&i.Severity,
		&i.Slot,
		&i.RecommendedAction,
		&i.Evidence,
		&i.CreatedAt,
	)
	return i, err
}

const insertLifecycleEvent = `-- name: InsertLifecycleEvent :one
INSERT INTO lifecycle_events (
    id, transaction_id, signature, bundle_id, stage, slot, latency_ms, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, transaction_id, signature, bundle_id, stage, slot, latency_ms, metadata, created_at
`

type InsertLifecycleEventParams struct {
	ID            string      `json:"id"`
	TransactionID string      `json:"transaction_id"`
	Signature     pgtype.Text `json:"signature"`
	BundleID      pgtype.Text `json:"bundle_id"`
	Stage         string      `json:"stage"`
	Slot          pgtype.Int8 `json:"slot"`
	LatencyMs     pgtype.Int8 `json:"latency_ms"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) InsertLifecycleEvent(ctx context.Context, arg InsertLifecycleEventParams) (LifecycleEvent, error) {
	row := q.db.QueryRow(ctx, insertLifecycleEvent,
		arg.ID,
		arg.TransactionID,
		arg.Signature,
		arg.BundleID,
		arg.Stage,
		arg.Slot,
		arg.LatencyMs,
		arg.Metadata,
	)
	var i LifecycleEvent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Signature,
		&i.BundleID,
		&i.Stage,
		&i.Slot,
		&i.LatencyMs,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecoveryAction = `-- name: InsertRecoveryAction :one
INSERT INTO recovery_actions (id, transaction_id, decision_id, label, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transaction_id, decision_id, label, status, created_at, updated_at
`

type InsertRecoveryActionParams struct {
	ID            string      `json:"id"`
	TransactionID string      `json:"transaction_id"`
	DecisionID    pgtype.Text `json:"decision_id"`
	Label         string      `json:"label"`
	Status        string      `json:"status"`
}

func (q *Queries) InsertRecoveryAction(ctx context.Context, arg InsertRecoveryActionParams) (RecoveryAction, error) {
	row := q.db.QueryRow(ctx, insertRecoveryAction,
		arg.ID,
		arg.TransactionID,
		arg.DecisionID,
		arg.Label,
		arg.Status,
	)
	var i RecoveryAction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.DecisionID,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBundles = `-- name: ListBundles :many
SELECT id, transaction_id, status, tip_lamports, target_slot, submitted_at, landed_at, failed_at, created_at FROM bundles ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListBundles(ctx context.Context, limit int32) ([]Bundle, error) {
	rows, err := q.db.Query(ctx, listBundles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bundle{}
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Status,
			&i.TipLamports,
			&i.TargetSlot,
			&i.SubmittedAt,
			&i.LandedAt,
			&i.FailedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartPoints = `-- name: ListChartPoints :many
SELECT id, series, point_time, payload, created_at FROM chart_points WHERE series = $1 AND point_time >= $2 ORDER BY point_time ASC
`

type ListChartPointsParams struct {
	Series    string             `json:"series"`
	PointTime pgtype.Timestamptz `json:"point_time"`
}

func (q *Queries) ListChartPoints(ctx context.Context, arg ListChartPointsParams) ([]ChartPoint, error) {
	rows, err := q.db.Query(ctx, listChartPoints, arg.Series, arg.PointTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChartPoint{}
	for rows.Next() {
		var i ChartPoint
		if err := rows.Scan(
			&i.ID,
			&i.Series,
			&i.PointTime,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleEvents = `-- name: ListLifecycleEvents :many
SELECT id, transaction_id, signature, bundle_id, stage, slot, latency_ms, metadata, created_at FROM lifecycle_events WHERE transaction_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListLifecycleEvents(ctx context.Context, transactionID string) ([]LifecycleEvent, error) {
	rows, err := q.db.Query(ctx, listLifecycleEvents, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LifecycleEvent{}
	for rows.Next() {
		var i LifecycleEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Signature,
			&i.BundleID,
			&i.Stage,
			&i.Slot,
			&i.LatencyMs,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgentDecisions = `-- name: ListRecentAgentDecisions :many
SELECT id, transaction_id, decision_type, title, summary, inputs, action, confidence_pct, created_at FROM agent_decisions ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentAgentDecisions(ctx context.Context, limit int32) ([]AgentDecision, error) {
	rows, err := q.db.Query(ctx, listRecentAgentDecisions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDecision{}
	for rows.Next() {
		var i AgentDecision
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.DecisionType,
			&i.Title,
			&i.Summary,
			&i.Inputs,
			&i.Action,
			&i.ConfidencePct,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailures = `-- name: ListRecentFailures :many
SELECT id, transaction_id, bundle_id, kind, title, severity, slot, recommended_action, evidence, created_at FROM failures ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentFailures(ctx context.Context, limit int32) ([]Failure, error) {
	rows, err := q.db.Query(ctx, listRecentFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Failure{}
	for rows.Next() {
		var i Failure
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.BundleID,
			&i.Kind,
			&i.Title,
			&i.Severity,
			&i.Slot,
			&i.RecommendedAction,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT id, signature, bundle_id, submission_kind, encoding, signatures, tx_count, status, stage, policy_mode, tip_lamports, requested_tip_lamports, floor_lamports, tip_source, target_slot, submitted_slot, processed_slot, confirmed_slot, finalized_slot, leader, retry_attempt, failure_kind, agent_decision_id, memo, created_at, submitted_at, processed_at, confirmed_at, finalized_at, failed_at, updated_at FROM transactions ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentTransactions(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listRecentTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Signature,
			&i.BundleID,
			&i.SubmissionKind,
			&i.Encoding,
			&i.Signatures,
			&i.TxCount,
			&i.Status,
			&i.Stage,
			&i.PolicyMode,
			&i.TipLamports,
			&i.RequestedTipLamports,
			&i.FloorLamports,
			&i.TipSource,
			&i.TargetSlot,
			&i.SubmittedSlot,
			&i.ProcessedSlot,
			&i.ConfirmedSlot,
			&i.FinalizedSlot,
			&i.Leader,
			&i.RetryAttempt,
			&i.FailureKind,
			&i.AgentDecisionID,
			&i.Memo,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.ProcessedAt,
			&i.ConfirmedAt,
			&i.FinalizedAt,
			&i.FailedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryActions = `-- name: ListRecoveryActions :many
SELECT id, transaction_id, decision_id, label, status, created_at, updated_at FROM recovery_actions ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecoveryActions(ctx context.Context, limit int32) ([]RecoveryAction, error) {
	rows, err := q.db.Query(ctx, listRecoveryActions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryAction{}
	for rows.Next() {
		var i RecoveryAction
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.DecisionID,
			&i.Label,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBundleStatus = `-- name: UpdateBundleStatus :one
UPDATE bundles SET status = $2, landed_at = COALESCE($3, landed_at), failed_at = COALESCE($4, failed_at)
WHERE id = $1 RETURNING id, transaction_id, status, tip_lamports, target_slot, submitted_at, landed_at, failed_at, created_at
`

type UpdateBundleStatusParams struct {
	ID       string             `json:"id"`
	Status   string             `json:"status"`
	LandedAt pgtype.Timestamptz `json:"landed_at"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

func (q *Queries) UpdateBundleStatus(ctx context.Context, arg UpdateBundleStatusParams) (Bundle, error) {
	row := q.db.QueryRow(ctx, updateBundleStatus,
		arg.ID,
		arg.Status,
		arg.LandedAt,
		arg.FailedAt,
	)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Status,
		&i.TipLamports,
		&i.TargetSlot,
		&i.SubmittedAt,
		&i.LandedAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRecoveryActionStatus = `-- name: UpdateRecoveryActionStatus :one
UPDATE recovery_actions SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, transaction_id, decision_id, label, status, created_at, updated_at
`

type UpdateRecoveryActionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateRecoveryActionStatus(ctx context.Context, arg UpdateRecoveryActionStatusParams) (RecoveryAction, error) {
	row := q.db.QueryRow(ctx, updateRecoveryActionStatus, arg.ID, arg.Status)
	var i RecoveryAction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.DecisionID,
		&i.Label,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions SET
    status = $2,
    stage = $3,
    signature = COALESCE($4, signature),
    bundle_id = COALESCE($5, bundle_id),
    tip_lamports = COALESCE($6, tip_lamports),
    target_slot = COALESCE($7, target_slot),
    submitted_slot = COALESCE($8, submitted_slot),
    processed_slot = COALESCE($9, processed_slot),
    confirmed_slot = COALESCE($10, confirmed_slot),
    finalized_slot = COALESCE($11, finalized_slot),
    leader = COALESCE($12, leader),
    retry_attempt = COALESCE($13, retry_attempt),
    failure_kind = COALESCE($14, failure_kind),
    agent_decision_id = COALESCE($15, agent_decision_id),
    submitted_at = COALESCE($16, submitted_at),
    processed_at = COALESCE($17, processed_at),
    confirmed_at = COALESCE($18, confirmed_at),
    finalized_at = COALESCE($19, finalized_at),
    failed_at = COALESCE($20, failed_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, signature, bundle_id, submission_kind, encoding, signatures, tx_count, status, stage, policy_mode, tip_lamports, requested_tip_lamports, floor_lamports, tip_source, target_slot, submitted_slot, processed_slot, confirmed_slot, finalized_slot, leader, retry_attempt, failure_kind, agent_decision_id, memo, created_at, submitted_at, processed_at, confirmed_at, finalized_at, failed_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID              string             `json:"id"`
	Status          string             `json:"status"`
	Stage           string             `json:"stage"`
	Signature       pgtype.Text        `json:"signature"`
	BundleID        pgtype.Text        `json:"bundle_id"`
	TipLamports     int64              `json:"tip_lamports"`
	TargetSlot      pgtype.Int8        `json:"target_slot"`
	SubmittedSlot   pgtype.Int8        `json:"submitted_slot"`
	ProcessedSlot   pgtype.Int8        `json:"processed_slot"`
	ConfirmedSlot   pgtype.Int8        `json:"confirmed_slot"`
	FinalizedSlot   pgtype.Int8        `json:"finalized_slot"`
	Leader          pgtype.Text        `json:"leader"`
	RetryAttempt    int32              `json:"retry_attempt"`
	FailureKind     pgtype.Text        `json:"failure_kind"`
	AgentDecisionID pgtype.Text        `json:"agent_decision_id"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	FinalizedAt     pgtype.Timestamptz `json:"finalized_at"`
	FailedAt        pgtype.Timestamptz `json:"failed_at"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.Signature,
		arg.BundleID,
		arg.TipLamports,
		arg.TargetSlot,
		arg.SubmittedSlot,
		arg.ProcessedSlot,
		arg.ConfirmedSlot,
		arg.FinalizedSlot,
		arg.Leader,
		arg.RetryAttempt,
		arg.FailureKind,
		arg.AgentDecisionID,
		arg.SubmittedAt,
		arg.ProcessedAt,
		arg.ConfirmedAt,
		arg.FinalizedAt,
		arg.FailedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Signature,
		&i.BundleID,
		&i.SubmissionKind,
		&i.Encoding,
		&i.Signatures,
		&i.TxCount,
		&i.Status,
		&i.Stage,
		&i.PolicyMode,
		&i.TipLamports,
		&i.RequestedTipLamports,
		&i.FloorLamports,
		&i.TipSource,
		&i.TargetSlot,
		&i.SubmittedSlot,
		&i.ProcessedSlot,
		&i.ConfirmedSlot,
		&i.FinalizedSlot,
		&i.Leader,
		&i.RetryAttempt,
		&i.FailureKind,
		&i.AgentDecisionID,
		&i.Memo,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.ProcessedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.FailedAt,
		&i.UpdatedAt,
	)
	return i, err
}
